metricbeat.modules:
- module: docker
  metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
output.elasticsearch:
 hosts: ["localhost:9200"]
setup.kibana:
 host: "localhost:5601"

